### PR TITLE
fix modulo bias in random number generation

### PR DESCRIPTION
**Pull request by unsubtract**
This patch will ensure that every character is always picked with equal probability.
[This StackOverflow answer](https://stackoverflow.com/a/10984975) does a good job explaining what modulo bias is and how it can be fixed.

### CODE REVIEW

**Comment by KanzenTaiwa** [comment]
Can you explain a little bit more why (if you know of course)  this happens?, and did you notice any change if this equality has improved the entropy level of each generation?

**Comment by KanzenTaiwa** [comment]
Just wanna know here because I'm wondering to change rand() by a safer method using a "Cryptographically secure pseudorandom number generator", which will make the usage of rcg safer even for generating passwords.

**Comment by unsubtract** [comment]
> Can you explain a little bit more why (if you know of course) this happens?, and did you notice any change if this equality has improved the entropy level of each generation?

Any time you generate a random number using *any method* and try to restrict it to some smaller range using modulo, there will be a bias (unless the range of possible random numbers (e.g. 0 - `RAND_MAX`) is evenly divisible by said smaller range). The StackOverflow link, as well as [this article](https://research.kudelskisecurity.com/2020/07/28/the-definitive-guide-to-modulo-bias-and-how-to-avoid-it/), do a very good job at explaining why.

As an example, imagine that the generator only generates numbers in the range of 0-255, and we want to use modulo to achieve a range of 0-99 (mod 100). If the generator returns any number 0-99 or 100-199, taking mod 100 maps them evenly into our 0-99 range as expected. Notice however that with numbers 200-255, it is only possible to map to a range of 0-55. These numbers have been mapped more often than 56-99, making them more likely to be chosen and leading to a bias.

In the above example, the bias can be fixed by essentially rejecting the number and picking a new one if we get 200-255. This is called rejection sampling. All random number generators that allow you to change their range are just doing this internally.

> Just wanna know here because I'm wondering to change rand() by a safer method using a "Cryptographically secure pseudorandom number generator", which will make the usage of rcg safer even for generating passwords.

I was actually intending on making a second patch to do exactly that. You can use the [`getrandom()`](https://man7.org/linux/man-pages/man2/getrandom.2.html) syscall to obtain cryptographically-secure random bytes which come from the same source as `/dev/urandom`.

**Comment by KanzenTaiwa** [comment]
so, I think will be going to use a safer option, knowing that rand() has this issue then I'm going to change, just gonna search a little further about how to implement and if is there any option that is better than getrandom() or etc, and by the way, I will verify your commit, and see if I can still use what you send me and thank you very much for your time.

**Pull request closed without merging**
