### PR TITLE
Fix readme typos

### PR DESCRIPTION
**Pull request by Seven0492**
I took some liberties, but I did my best not to change the intent behind the words.

But do tell me if something's unclear!

I also have some other changes I'd like to propose, but that'll be in a subsequent pull request.

### CODE REVIEW

**Comment by KanzenTaiwa** [comment]
I check it out here the changes you've done, It's pretty good, I will search a little further about what you send me on "issues" and the project will be better for supporting

**Comment by Seven0492** [comment]
Oh, and, forgot to mention it, but it's a bit silly looking when you see the big ASCII R.C.G. logo, and just below it says:
- Formerly: Random Character Generator

 So what is it then? :P

And then you look just below and it says:
- Rcg or Random Character Generator is an open-source [...]

I mean, that gave me a good laugh, but it's probably not what you intended.

**Comment by KanzenTaiwa** [comment]
Actually, I intended to gave some context of it, but that's ok.

**Comment by Seven0492** [comment]
@KanzenTaiwa

Oh! So you meant it to be a context flag? That's cool too, personally, I'd have recommended highlighting the name in the paragraph instead, so it's not redundant, but, I like the effect of it being in bold above the paragraph too, it's just, another thing to consider.

**Comment by Seven0492** [comment]
Oh, and, it's strange, because the second fixed typo in the merge is 'a' to -> 'an', but it reappeared in the readme last I checked, weird.

**Pull request merged**
