### PR TITLE
general Makefile improvements

### PR DESCRIPTION
**Pull request by unsubtract**
Various changes to make the Makefile cleaner and more portable, following common conventions. See the commit messages for details.

### CODE REVIEW

**Comment by Seven0492** [comment]
Just curious, why rename the makefile so it has an uppercase?

Is that the standard in some way or personal preference?

**Comment by KanzenTaiwa** [comment]
Hello man, amavect already did a lot of modifications to it, i would like to know if you can check it out and see it

**Comment by unsubtract** [comment]
> Just curious, why rename the makefile so it has an uppercase?
> 
> Is that the standard in some way or personal preference?

Refer to the commit message under 14bb656

Having the M be uppercase is the standard and preferred convention, and my system wouldn't even recognize the Makefile otherwise

**Comment by unsubtract** [comment]
The merge conflict should now be resolved. Copying the list of changes from the old commit (crossed out ones are ones that already got merged beforehand, **bolded** ones that are only applicable to said merge):
- ~~The 'M' in Makefile must be capitalized or else some implementations (such as the one I'm using) fail to find it~~
- ~~Never hard-code sudo(8) in any sorts of scripts ever. Its not guarenteed to actually exist on the user's machine (on my system I only have doas(1), no sudo) and it should be the user's decision on whether to a script as root. Running scripts that contain sudo hard-coded in general is dangerous because its a very easy way for someone to introduce malware.~~
- ~~install(1) can be used to both copy the binary and make it executable~~ **(I have added the `-Dm755` flag to correctly create directories and set the permissions)**
- There really isn't any reason to make rm, ~~mv, etc.~~ into their own variables. Any system that has make will have these same standard utilities.
- The 'run' rule is pretty useless, most people know how to run a program.
- CFLAGS are used for compilation, while LDFLAGS are used for linking (most compilation flags do nothing when linking and vice-versa). There also shouldn't be a space when passing -I or -l (I don't know how GCC allowed this, most compilers don't).
- ~~-Wextra will enable some more warnings not covered by -Wall~~
- It's assumed that all Unix-like systems install binaries to /something/bin, so the convention is to make the 'something' part into its own variable called PREFIX (in this case defaulting to /usr/local). The DESTDIR variable is a convention that can basically allows you to change what directory your Makefile considers to be root, usually used to assist with packaging for distros (and passed directly on the command line rather than being in the Makefile).
- ~~You forgot to add the rcg binary itself to the 'clean' rule.~~
- CC doesn't need to be hardcoded, it defaults to 'cc' which is the standard symlink for the system's C compiler.
- 'uninstall' doesn't necessarily depend on 'clean', a user could want to uninstall the program from their system without removing the local build.
- **You probably shouldn't be building your object files in the directory named "src"**

**Comment by unsubtract** [comment]
Converting to draft until #13 is merged as the two are currently incompatible

**Review by KanzenTaiwa — COMMENTED** [review]
I will change here some things just to explicit some details that may cause some confusion, but it seems very good actually.

**Pull request merged**
